packages:
  - .

supportedArchitectures:
  os:
    - current
    - win32
  cpu:
    - current
    - x64

onlyBuiltDependencies:
  - electron
  - esbuild

allowBuilds:
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
