import type { PlatformPort } from "@application/ports/platform-port";

export const IPC_CHANNELS = {
  listNovels: "novels:list",
  importNovelProject: "novels:import-project",
  getDiagnostics: "app:diagnostics",
  createNovel: "novels:create",
  generateNovelPlan: "novels:plan:generate",
  listChapters: "chapters:list",
  getChapter: "chapters:get",
  saveChapter: "chapters:save",
  createChapter: "chapters:create",
  updateChapterPlan: "chapters:plan:update",
  deleteChapter: "chapters:delete",
  reorderChapters: "chapters:reorder",
  listStoryStructure: "structure:list",
  saveVolume: "structure:volumes:save",
  deleteVolume: "structure:volumes:delete",
  reorderVolumes: "structure:volumes:reorder",
  saveScene: "structure:scenes:save",
  deleteScene: "structure:scenes:delete",
  reorderScenes: "structure:scenes:reorder",
  saveContextSnapshot: "context:snapshots:save",
  listContextSnapshots: "context:snapshots:list",
  saveUsage: "usage:save",
  listUsage: "usage:list",
  listModelProfiles: "models:profiles:list",
  saveModelProfile: "models:profiles:save",
  deleteModelProfile: "models:profiles:delete",
  testModelConnection: "models:connection:test",
  generateChapter: "generation:chapter:start",
  generationProgress: "generation:chapter:progress",
  listChapterCandidates: "generation:candidates:list",
  acceptChapterCandidate: "generation:candidates:accept",
  rejectChapterCandidate: "generation:candidates:reject",
  cancelGeneration: "generation:chapter:cancel",
  listFindings: "quality:findings:list",
  updateFinding: "quality:findings:update",
  listFactProposals: "quality:proposals:list",
  updateFactProposal: "quality:proposals:update",
  listChapterVersions: "chapters:versions:list",
  createChapterSnapshot: "chapters:versions:create",
  listBibleSections: "bible:sections:list",
  saveBibleSection: "bible:sections:save",
  listStoryEntities: "bible:entities:list",
  saveStoryEntity: "bible:entities:save",
  deleteStoryEntity: "bible:entities:delete",
  listTimelineEvents: "continuity:timeline:list",
  saveTimelineEvent: "continuity:timeline:save",
  deleteTimelineEvent: "continuity:timeline:delete",
  listForeshadowThreads: "continuity:foreshadow:list",
  saveForeshadowThread: "continuity:foreshadow:save",
  deleteForeshadowThread: "continuity:foreshadow:delete",
  listCharacterStates: "continuity:character-states:list",
  saveCharacterState: "continuity:character-states:save",
  deleteCharacterState: "continuity:character-states:delete",
  createGenerationDraft: "generation:create-draft",
  listGenerationBatches: "generation:batches:list",
  listGenerationJobs: "generation:jobs:list",
  setBatchStatus: "generation:batches:status",
  updateGenerationJob: "generation:jobs:update",
  startBackgroundBatch: "generation:batches:start-background",
  pauseBackgroundBatch: "generation:batches:pause-background",
} as const;

export type AmyNovelApi = PlatformPort;
